SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[Unit_READ_BY_PROJECT_CODE]
@ProjectCode NVARCHAR(50) = NULL
AS
BEGIN	
	SELECT	* 
	FROM  [dbo].[UnitView]
	WHERE [Unit_ProjectCode] = @ProjectCode
END

GO
