CREATE TABLE [dbo].[UserProfile]
(
[UserId] [int] NOT NULL IDENTITY(1, 1),
[UserName] [nvarchar] (56) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UserProfile] ADD CONSTRAINT [PK__UserProf__1788CC4C50184CE6] PRIMARY KEY CLUSTERED  ([UserId]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[UserProfile] ADD CONSTRAINT [UQ__UserProf__C9F284562C424A9B] UNIQUE NONCLUSTERED  ([UserName]) ON [PRIMARY]
GO
